name: Build cips@nyist dev ver.

on:
  push:
    branches: [ "nyist-pxe-dev" ]
  pull_request:
    branches: [ "nyist-pxe-dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Send start notification to WeCom
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK_URL }}
      with:
        #msgtype: text
        #content: "NYIST-CIPS/netboot ğŸ”±nyist-pxe-dev æµ‹è¯•æ„å»ºå·²å¼€å§‹ğŸš€"
        msgtype: template_card
        template_card: '{"msgtype":"template_card","template_card":{"card_type":"news_notice","source":{"icon_url":"https://github.githubassets.com/favicons/favicon-dark.png","desc":"GitHub Actions è‡ªåŠ¨é€šçŸ¥","desc_color":0},"main_title":{"title":"${{GITHUB_REPOSITORY}} ğŸ”±${{GITHUB_REF_NAME}}å·¥ä½œæµå·²å¯åŠ¨ğŸš€","desc":" å½“å‰äº‹ä»¶ï¼š${{GITHUB_EVENT_NAME}} "},"card_image":{"url":"https://gh-card.dev/repos/${{GITHUB_REPOSITORY}}.png","aspect_ratio":2.25},"image_text_area":{"type":1,"url":"https://github.com/${{GITHUB_REPOSITORY}}/commit/${{GITHUB_WORKFLOW_SHA}}","title":"${{GITHUB_ACTOR}}","desc":"${{GITHUB_WORKFLOW_SHA}}","image_url":"https://avatars.githubusercontent.com/u/${{GITHUB_ACTOR_ID}}"},"vertical_content_list":[{"title":"Actionså·²å¼€å§‹æ‰§è¡Œ","desc":"æ•¬è¯·å…³æ³¨åç»­æç¤º"}],"horizontal_content_list":[{"keyname":"Actionså‘èµ·äºº","value":"${{GITHUB_TRIGGERING_ACTOR}}"},{"keyname":"Actions ID","value":"${{GITHUB_RUN_ID}}","type":1,"url":"https://github.com/${{GITHUB_REPOSITORY}}/actions/runs/${{GITHUB_RUN_ID}}"},{"keyname":"æ„å»ºæˆæœ","value":"è¯·ç¨å","type":2,"media_id":"1"}],"jump_list":[{"type":1,"url":"https://github.com/${{GITHUB_REPOSITORY}}","title":"${{GITHUB_REPOSITORY}} ä»“åº“é¡µé¢"}],"card_action":{"type":1,"url":"https://work.weixin.qq.com/?from=openApi","appid":"APPID","pagepath":"PAGEPATH"}}}'
        
    - name: Build the Docker image
      run: docker build -t localbuild -f Dockerfile .

    - name: Build site
      run: docker run --rm -v $(pwd):/buildout localbuild

    - name: Copy pxe background image
      run: cp pxe_bg.png buildout/

    - name: Create buildout archive
      run: |
        cd buildout
        zip -r buildout.zip .

    - name: Upload buildout artifact
      uses: actions/upload-artifact@v2
      with:
        name: buildout-artifact
        path: buildout/buildout.zip

    - name: Send end notification to WeCom
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK_URL }}
      with:
        msgtype: text
        content: "NYIST-CIPS/netboot ğŸ”±nyist-pxe-dev æµ‹è¯•æ„å»ºæˆåŠŸâœ¨"
